--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DerCooleVonDem/EconomyLite
build-by-default: true
branches:
- main
projects:
  EconomyLite:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.6

...
